### ISSUE TITLE
issue with import feature

### ISSUE THREAD

**Issue by bnap00** [jven/studyopenings#36]
importing a pgn with a valid move says its an illegal move
![Screenshot from 2021-08-04 10-29-51](https://user-images.githubusercontent.com/10740210/128125186-6dec7ae3-c0e0-4059-a854-2fcbe7292a39.png)
it says `Nge2` is not a legal move, but its a legal move, `Nce2` is not a legal move
![Screenshot from 2021-08-04 10-30-36](https://user-images.githubusercontent.com/10740210/128125189-cad586d5-6454-41cd-b49f-aff38c5d1dea.png)

**Comment by jven** [comment]
Hi, the PGN parsing library used by studyopenings is very strict and it likely needs you to input "Ne2" instead of "Nge2". The "g" disambiguation is not needed because no other knight (i.e. the pinned knight) can move to e2.

Instead of manually fixing your PGNs, if you upload them to lichess and re-export them from there, you should get back a "strict" PGN.

**Comment by jven** [comment]
Feel free to reopen the issue if that doesn't help you!
